### ISSUE TITLE
whrong command in your official thales doc

### ISSUE THREAD

**Issue by melvintj** [anugram/ciphertrust-cte-ansible-role#1]
Hi Anugram, thank you for creating the CTE-Ansible-role.
I have seen a small typo in your official documentation and thought this would be the easiest to contact you.

https://supportportal.thalesgroup.com/community?id=community_blog&sys_id=9f0bde584704b190c0e42e61e36d4307
The following command i was stuck at because i have no prior experience to ansible;
$ ansible-galaxy install anugram.ciphertrust-cte-ansible-role
But i found your other page and it has the word "role" added so i was able to get it to work (https://galaxy.ansible.com/ui/standalone/roles/anugram/ciphertrust_cte_ansible_role/)
It must be changed to;
$ ansible-galaxy role install anugram.ciphertrust_cte_ansible_role 

Please edit the supportportal link from tales with the role command added.

**Comment by anugram** [comment]
@melvintj thanks for pointing it out. 
This is definitely a documentation issue. 
Will make the necessary changes.
